### PR TITLE
[WIP] Allow loading dbpatch from remote connection

### PR DESCRIPTION
**Pull request by strk**
See #13

### CODE REVIEW

**Comment by strk** [comment]
TODO:
- [ ] Have `make install` put that file in contrib/dbpatch-{version} under PostgreSQL share dir
- [ ] Allow testing the non-extension install

**Comment by strk** [comment]
NOTE: with the non-extension based load I'm hard-coding a schema name `_patches`, is this acceptable ? Or should schema be unspecified to give more flexibility ? Note that lack of schema specification opens the door to security concerns, whereas an unprivileged user may call a SECURITY DEFINER function (not defined by this extension but possibly defined by users of it) to execute an arbitrary function (installed by the attacker in a schema other than the one in which `dbpatch` would be installed).

So, my vote is we do the hard-coding and just have to agree on the name (`_patches` is what curretly BDE components use for it).

Beside, the extension configuration is already for it to NOT be relocatable, but does NOT specify a schema name, I think we could also hard-code the schema name there.

**Comment by strk** [comment]
Filed PR #15 to propose the hardcoded installation schema.

**Comment by strk** [comment]
Alright, now I'm happy.
The .sql script to load the function and table outside of the EXTENSION mechanism is only installed a sa template, and a `dbpatch-loader` script is installed (in PostgreSQL bin directory) that allows you to load the extension with or without the extension mechanism and at the same time specify the target schema (which defaults to first schema in search_path if not specified, same as with the EXTENSION mechanism) and the target version (which defaults to the default version in extension's control file).

Signature is:
```
Usage: ./dbpatch-loader [--no-extension] [--version <ver>] <dbname> [<schema>]
```

Updated TODO:

- [ ] Add tests for the script, ideally with both extension and non-extension loads
- [ ] Ensure debian package (`make deb`) includes the `dbpatch-{version}.sql` script
- [ ] Update README with instructions to install/upgrade w/out EXTENSION support

**Comment by imincik** [comment]
> NOTE: with the non-extension based load I'm hard-coding a schema name _patches, is this acceptable ? 
I am OK with, but it looks like not needed now.

Great work @strk . That was much smoother than I thought.

**Comment by strk** [comment]
Cool, thanks for review !

**Pull request merged**
